### ISSUE TITLE
CEZ

### ISSUE THREAD

**Issue by MattXcz** [slesinger/HomeAssistant-PREdistribuce#1]
Dobrá práce... 
mám přes curl a volání HA API vlastní senzor pro CEZ (https://www.cezdistribuce.cz/cs/pro-zakazniky/spinani-hdo.html)
Možná by bylo příjemné zakomponovat do pluginu i ČEZ =)

**Comment by slesinger** [comment]
Zdravim, muzete mi poskytnout to, co mate ted at znovu neobjevuji kolo? Zkusim CEZ zapracovat.

**Comment by MattXcz** [comment]
Jedná se o soubor php, který data čte a zpracuje:
[HDO(php).txt](https://github.com/slesinger/HomeAssistant-PREdistribuce/files/4993685/HDO.php.txt)
využíva include kalendář:
[Kalendar(php).txt](https://github.com/slesinger/HomeAssistant-PREdistribuce/files/4993714/Kalendar.php.txt)

Celý proces se pak odešle přes API do HomeAssistatnu:
[HDO(SH).txt](https://github.com/slesinger/HomeAssistant-PREdistribuce/files/4993704/HDO.SH.txt)

**Comment by MattXcz** [comment]
![image](https://user-images.githubusercontent.com/14542099/88778089-5a5ca580-d188-11ea-8921-abffabdd9163.png)

Lovalace yaml:

```
cards:
  - entity: sensor.hdo
    hours_to_show: 48
    icon: 'mdi:flash'
    type: sensor
    unit: (aktualní tarif)
  - content: |-
      ## Zbývá : {{(as_timestamp(strptime((state_attr("sensor.hdo","do")),
        ("%H:%M")) | 
         default(0)) - as_timestamp(now()) ) | timestamp_custom("%H")|int-1}} hodin      {{(as_timestamp(strptime((state_attr("sensor.hdo","do")), ("%H:%M")) |
         default(0)) - as_timestamp(now()) ) | timestamp_custom("%M")|int}} minut 
         ####  {{state_attr("sensor.hdo","cena") }}
    type: markdown
type: vertical-stack
```
