### ISSUE TITLE
Additional sensors not added

### ISSUE THREAD

**Issue by Kratax** [slesinger/HomeAssistant-PREdistribuce#16]
Hi,
Thanks a lot for the add on. I tried to configure the other sensors as per below but still in the HA, there is only one sensor showing on off depending on the rate... Any advice what to correct? thanks a lot.

  - platform: predistribuce
    receiver_command_id: 605
    periods:
      - name: "HDO baterie 3h"
        minutes: 120
      - name: "HDO baterie 4h"
        minutes: 160

**Comment by eMeF1** [comment]
Here is how I got it work. But frankly I am not a programmer and this is what ChatGPT suggested so hard to say how clean this solution is.

**binary_sensor.py**

raplece
`        self._attr_unique_id = f"{DOMAIN}-hdo-{conf_cmd}"`
with
`        self._attr_unique_id = f"{DOMAIN}-hdo-{conf_cmd}-{minutes}"`

**configuration.yaml**
```
binary_sensor:
  - platform: predistribuce
    receiver_command_id: 565
    sensor_name: "PRE HDO"
    periods:
      - name: "HDO shower"
        minutes: 10
      - name: "HDO living room heating"
        minutes: 120

sensor:
  - platform: predistribuce
    receiver_command_id: 565
```

I would like too have also "HDO čas do **vysokého** tarifu" apart from "HDO čas do **nízkého** tarifu" but I couldn't make GPT to make it work.
