### ISSUE TITLE
 [binary_sensor.predistribuce]: [name] is an invalid option for [binary_sensor.predistribuce].

### ISSUE THREAD

**Issue by jirimissbach** [slesinger/HomeAssistant-PREdistribuce#4]
Instalace pomocí HACS, HA core-2021.6.5, konfigurace přesně dle návodu

# Example configuration.yaml entry for showing current HDO state and HTML for rendering a time schedule
binary_sensor:
  platform: predistribuce
  name: nocni proud
  receiver_command_id: 605

Check configuration hlásí

Invalid config for [binary_sensor.predistribuce]: [name] is an invalid option for [binary_sensor.predistribuce]. Check: binary_sensor.predistribuce->name. (See ?, line ?).

Netuším co dělám  špatně, skoušel jsem i jiný formát ale slále nejsem schopen senzor pojmenovat. Děkuji za pomoc

**Comment by slesinger** [comment]
Ja to pouzivam takto:
```
binary_sensor:
  - platform: predistribuce
    receiver_command_id: 605
    periods:
      - name: HDO Pračka
        minutes: 30
      - name: HDO Myčka
        minutes: 150
```
pro indikaci zda spotrebic stihne dobehnout v ramci levneho proudu a potam take sensor pro vlastni HDO takto:
```
sensor:
  - platform: predistribuce
    receiver_command_id: 605
```
Potiz je, ze mate ```name``` na stejne urovni vnoreni jako ```platform```.

Dale pouzivam vizualizaci v ramci Lovelace karty
```
type: custom:html-card
title: PRE tarif
content: |
  [[binary_sensor.hdo_aktualne.attributes.html_values]]
```
ktera vypada dost podobne, jako to ma PRE na svych strankach.
